language: node_js
node_js:
- '8'
script: "yarn install & yarn build"
deploy:
  provider: s3
  access_key_id: AKIAJU2LPWQJZWAP2ETA
  secret_access_key:
    secure: Mgmd2OI8t16pKcvqZm3R4SRa+iFpe6Lk2ce3onsbWa9ojRR0r2cx66RPt15hKe7Ts4Wa09GIZfB24HheGvA1pRh8mfVr5B6EOOupRNsCSRhLidceN/KRMhp5l4ls2jnC+O+mQiysDSLrm6MmmD4t1U512fSA1mLvVtHs23+dbIhyy6j8DoWBgfT4R09UYCLu/ErrcVBgLRi08JmPdSy7sFF7WrmfKn0QYXGk27DlSyZyMkTlgp45XOOnjIv7nbRnndKM1XjXtVoKjd3L9JGXwoDZwy1dX1Tf5T3hDy/hKXxzJ40pqn1/24pT4qL5rx0g8AOqQAdKVAMS6eSqWf1emHTLBihI/zEMfIdGAoA1KwOOPzfdZLnSsryhgWocaVlcIVITr9LVd0zZOfNdjOnM6Uh6ABq/N0fO8+ReFxx1FZzUp7YveWJWGSKUfycx20RsofOC5dBYVT6xYOV2V0RMrJmoE2iOZE+BVF7/nKoaYq94BHjK785qhaZuQKA2I2Vf8dGFZAl7D6XJQicFIlXLreHA6omHnXbBeH6BRaj9aZfhZ8H78dhSeEZ3eOr7hqXuJnRXpQ+JBhVm2r8PSsUMwNub7w4XUs1pNcwJcGLkRF7U47GVESEbtUVI6n0JAd22m9lylcE3iBycuNujqyPVb3NWMayDKytzjzV/qGsVetU=
  bucket: html-a11y.com
  local-dir: build
  on:
    repo: ibarczewski/html-a11y
